### ISSUE TITLE
Task Tracker

### ISSUE THREAD

**Issue by Naman-ntc** [r2e-project/r2e-test-server#2]
* [x] Run everything inside the fut_module?
* [x] Support classes
  * [x] exec "ref_class" source code (ref_class should have classname aliases replaced)
  * [x] for codegen -- frontend should send updated class not updated method
* [x] Support multiple funclasses
  * [x] accept multiple funclasses as arguments
  * [x] ref both of them
  * [x] execute all tests
* [ ] For the self-equivalence setup -- we should mock the ground truth function as sent from frontend -- i.e. exec_and_compile of the function or class
  * this would make the two setups symmetric and avoid any issues
* [x] implement a main cli method which starts the server
